services:
  ipinfo:
    image: honeok/nginx:1.29.3-alpine
    container_name: ipinfo
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/ipinfo.conf:/etc/nginx/conf.d/ipinfo.conf
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=256m
    network_mode: bridge
