---
name: "Dependabot Merge"

on:
  pull_request:

jobs:
  dependabot:
    name: "Dependabot Merge"
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "Fetch Dependabot metadata"
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ github.token }}

      - name: "Approve and Auto merge"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --squash --auto "$PR_URL"
